import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/ThemeProvider";
import { cn } from "@/lib/utils";
import ReduxStoreProvider from "@/lib/ReduxStoreProvider";
import { Toaster, toast } from 'sonner'
const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "min-h-screen bg-background")}>
        <ThemeProvider
          attribute="class"
          themes={["light", "dark"]}
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange={false}
        >
          <ReduxStoreProvider>
             <Toaster position="top-right" richColors closeButton theme="dark"/>
            {children}
          </ReduxStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
